### ISSUE TITLE
schema변경 - totalInvestment 필드 삭제, investor 모델 investment 모델로 변경

### ISSUE THREAD

**Issue by taeyeonkim94** [2-ViewMyStartup-2-FE/2-ViewMystartup-2team-BE#21]
## 설명
totalInvestment 필드를 삭제하고 백엔드에서 tatalInvesment 값이 필요할 때 연산을 해서 리턴하게 변경

## TO-DO
- [x] totalInvesment 필드 삭제
- [x] totalInvesment 값이 필요한 곳에 actualInvesment와 virtualInvesment 값을 합산해서 리턴
- [x]  amount 필드 데이터 타입 BigInt로 변경
- [x] investor 모델을 invsetment 모델로 변경
