### ISSUE TITLE
Compare기본데이터불러오는구조 완성하기

### ISSUE THREAD

**Issue by bangsinchur** [2-ViewMyStartup-2-FE/2-ViewMystartup-2team-BE#23]
## TO-DO
- [x] Compare페이지에서 불러올 api 완성하기,
- [x] CreatedAt 필드 넣기,
- [x] 기본데이터에 createdAt필드 추가하기.
