### ISSUE TITLE
CompanyDetail API

### ISSUE THREAD

**Issue by GGON123** [2-ViewMyStartup-2-FE/2-ViewMystartup-2team-BE#31]
## TO-DO
- [x] companyDetail Route 생성
- [x] companyDetail Controller 생성
- [x] companyDetail http 테스트 파일 생성
- [x] struct.js PatchInvestment 추가
