### ISSUE TITLE
기업 상세 페이지 - investments get API

### ISSUE THREAD

**Issue by GGON123** [2-ViewMyStartup-2-FE/2-ViewMystartup-2team-BE#33]
## TO-DO
- [ ] API endpoint 설정 (/api/investments2/:id )
- [ ] investments GET Controller 생성(비지니스 로직 생성)
- [ ] investments GET Route 생성
