### ISSUE TITLE
Count get api 생성

### ISSUE THREAD

**Issue by annylee0723** [2-ViewMyStartup-2-FE/2-ViewMystartup-2team-BE#4]
## 설명
비교 현황 페이지 내 사용될 get api 생성

## TO-DO
- [x] API endpoint 설정 (`/api/companies/counts `)
- [x] Count GET Route 생성
- [x] Count GET Controller 생성(비지니스 로직 생성)
- [x] App.js에 라우트 추가
- [x] express(http) 파일 생성

## 기타
요구사항 as-is를 to-be로 수정하여 반영
![Screenshot 2024-09-26 at 2 42 05 PM](https://github.com/user-attachments/assets/ab725a07-53ec-4c70-a37a-d213c5e9a273)
